#!/usr/bin/env python3
import argparse
import plotly.express as px

# reads in the data arrays from file
# file will contain 1 array per line, as plain string, e.g:
#   ['abc', 'def']
#
# we will eval the string to convert it to an actual Python array
def read_values_from_file(fname):
    with open(fname) as f:
        parents = eval(f.readline())
        children = eval(f.readline())
        values = eval(f.readline())

    # parents = the parent node name
    # children = the child node name
    # values = array of abitrary int values, since we don't have a true count value to use here
    data_dic = dict(
        parents = parents,
        children = children,
        values = values
    )
    return data_dic

# creates a hierarchical sunburst graph given an input file
# containing the plotly arrays generated by convert_phylo_xml.py script
def plot_sunburst(input_file):
    data = read_values_from_file(input_file)

    fig = px.sunburst(
        data,
        parents="parents",
        names="children",
        values="values",
    )
    fig.show()

################# main #################
parser = argparse.ArgumentParser(description='Generate a Plotly sunburst graph')
parser.add_argument('-i', '--input', dest='input', help='plotly input file path, output from the convert_phylo_xml script', required=True)
args = parser.parse_args()

input_file = args.input
plot_sunburst(input_file)